spring:
  application:
    name: skillMatch
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skill_match
    username: root
    password: g091600jiof
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.skillmatch.domain.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    com.skillmatch: debug
gaoDe:
  key: ef38dd2c2cb2f91f4e3364e97ce78aef