spring:
  application:
    name: skillMatch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillMatch
    username: root
    password: g091600jiof
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.skillmatch.domain.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl